In [1]:
import numpy as np

### 入力から出力 (2 → 3)

In [2]:
# 2行3列
W1 = np.random.randn(2, 3)
W1

array([[-1.28775598,  0.94512411,  0.87046343],
       [-0.52581062,  0.60955164,  1.61880834]])

In [3]:
b1 = np.random.randn(3)
b1

array([-1.7480323 , -1.35548158,  0.25422996])

In [4]:
b1.shape

(3,)

In [5]:
# サンプル数：10、入力変数：2
x = np.random.randn(10, 2)
x

array([[-0.23510716, -0.54474071],
       [-0.7371161 , -1.94274815],
       [-0.49979072, -0.1302536 ],
       [ 0.07533001,  0.38547314],
       [-1.08480934, -1.33183649],
       [-0.17552199,  1.09783686],
       [ 0.70731414,  0.52476834],
       [ 0.21443512, -1.17527015],
       [ 0.07343774, -0.66721924],
       [-0.7403749 ,  1.35390402]])

In [6]:
x.shape

(10, 2)

In [7]:
W1.shape

(2, 3)

In [8]:
u1 = np.dot(x, W1) + b1
u1

array([[-1.1588412 , -1.90973462, -0.83225303],
       [ 0.22271097, -3.23635311, -3.53233956],
       [-1.03593508, -1.90724214, -0.39167521],
       [-2.04772485, -1.04931958,  0.94380911],
       [ 0.34923118, -3.19258417, -2.84604492],
       [-2.09925709, -0.85218338,  1.87863196],
       [-2.93480909, -0.36710852,  1.71942043],
       [-1.40620289, -1.86920163, -1.46164924],
       [-1.49177123, -1.69277838, -0.76194524],
       [-1.50650721, -1.22995332,  1.80147182]])

In [9]:
u1.shape

(10, 3)

In [10]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [11]:
sigmoid(u1)

array([[0.23887791, 0.12901067, 0.30316889],
       [0.55544874, 0.03782038, 0.02840595],
       [0.26193508, 0.129291  , 0.40331409],
       [0.11428247, 0.25935578, 0.71986844],
       [0.58643113, 0.03944575, 0.05488612],
       [0.10916905, 0.29897505, 0.86745391],
       [0.05045941, 0.40923989, 0.84805417],
       [0.19683365, 0.13363413, 0.18821521],
       [0.18365602, 0.1554108 , 0.31822408],
       [0.181457  , 0.2261896 , 0.858328  ]])

In [12]:
def relu(x):
    return np.maximum(0, x)

In [13]:
z1 = relu(u1)

In [14]:
z1

array([[0.        , 0.        , 0.        ],
       [0.22271097, 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.94380911],
       [0.34923118, 0.        , 0.        ],
       [0.        , 0.        , 1.87863196],
       [0.        , 0.        , 1.71942043],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.80147182]])

### 中間から出力(3 → 2)

In [15]:
W2 = np.random.randn(3, 2)
W2

array([[-0.67552476, -0.27927268],
       [ 0.20091011,  0.44940704],
       [-0.81923448, -1.07720719]])

In [16]:
b2 = np.random.randn(2)
b2

array([-2.06217926, -1.80577439])

In [17]:
u2 = np.dot(z1, W2) + b2

In [18]:
u2

array([[-2.06217926, -1.80577439],
       [-2.21262603, -1.86797148],
       [-2.06217926, -1.80577439],
       [-2.83538022, -2.82245235],
       [-2.29809357, -1.90330511],
       [-3.60121933, -3.82945024],
       [-3.47078776, -3.65794643],
       [-2.06217926, -1.80577439],
       [-2.06217926, -1.80577439],
       [-3.53800708, -3.74633278]])

In [19]:
def softmax(x):
    # オーバーフロー対策
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

In [20]:
y = softmax(u2[0])
y

array([0.43624767, 0.56375233])

In [21]:
np.argmax(y)

1

In [22]:
def softmax(x):
    if x.ndim == 2:
        # print(x)
        # print(x.max(axis=1, keepdims=True))
        # print(x.max(axis=1, keepdims=False))
        x = x - x.max(axis=1, keepdims=True)
        x = np.exp(x)
        x /= x.sum(axis=1, keepdims=True)
    elif x.ndim == 1:
        x = x - np.max(x)
        x = np.exp(x) / np.sum(np.exp(x))
    return x

In [23]:
softmax(u2)

array([[0.43624767, 0.56375233],
       [0.41467927, 0.58532073],
       [0.43624767, 0.56375233],
       [0.49676808, 0.50323192],
       [0.40256511, 0.59743489],
       [0.55681134, 0.44318866],
       [0.54665357, 0.45334643],
       [0.43624767, 0.56375233],
       [0.43624767, 0.56375233],
       [0.55189388, 0.44810612]])

### レイヤーとしてまとめていく
- 変数
    - パラメータ(params)
    - 勾配(grads)
- メソッド
    - 順伝播(forward)
    - 逆伝播(backward)

### Affine変換(線形変換)

In [24]:
class Affine:
    # パラメータの初期化
    def __init__(self, W, b):
        self.params = [W, b]
    
    # 順伝播
    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out

### ReLU関数（非線形変換）

In [25]:
class ReLU:
    def __init__(self):
        self.params = []
    
    def forward(self, x):
        return np.maximum(0, x)

In [26]:
W1 = np.random.randn(2, 3)
b1 = np.random.randn(3)

W2 = np.random.randn(3, 2)
b2 = np.random.randn(2)

In [27]:
class NN:
    # 重みの初期化(W, b)
    def __init__(self, n_in, n_hidden, n_out):
        # W, bの初期化
        W1 = np.random.randn(n_in, n_hidden)
        b1 = np.random.randn(n_hidden)
        W2 = np.random.randn(n_hidden, n_out)
        b2 = np.random.randn(n_out)

        # レイヤを全てまとめる
        self.layers = [
            Affine(W1, b1),
            ReLU(),
            Affine(W2, b2)
        ]
        
        # パラメータをまとめる
        self.params = []
        for layer in self.layers:
            self.params += layer.params
        
    # 推論
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [28]:
x = np.random.randn(10, 4)
x

array([[-1.5228392 ,  0.67961982, -0.25842739, -0.31467359],
       [ 1.08915441, -1.00687709,  0.72729976,  0.2480783 ],
       [ 0.04133412,  0.66597531, -0.85162347,  0.40069874],
       [ 0.20173301, -0.5688253 ,  0.18545424,  0.49244675],
       [-1.21347008, -1.05760381, -0.62386987,  2.61789118],
       [-1.81710558, -1.32238043,  1.30639784, -1.97508188],
       [ 0.71975344, -0.02426483, -1.81548817, -0.11756048],
       [-0.1581047 , -0.59847279,  1.16206256, -0.359768  ],
       [-0.43328363, -2.0865763 ,  2.1101603 ,  0.41742806],
       [-1.04979765, -0.10644411,  0.13225316,  1.99627276]])

In [29]:
model = NN(4, 10, 3)

In [30]:
model.predict(x)

array([[-2.5787897 ,  6.95390527,  0.02246604],
       [ 0.85805622, -0.07580892,  1.17657689],
       [ 0.39313952,  3.91444789,  2.11130729],
       [-0.40464265,  0.5911562 ,  0.39751844],
       [ 0.8417248 , 10.31262703,  3.09953569],
       [-4.683728  ,  5.00872554, -6.11981051],
       [ 0.76299733,  3.98855731,  2.17950938],
       [-2.11301232,  0.87498682, -0.84055935],
       [-2.23214596,  2.42819531, -1.04824794],
       [ 0.71192954,  7.32291932,  2.57350851]])

### 逆伝播


### Affine

In [31]:
class Affine:
    # パラメータの初期化
    def __init__(self, W, b):
        self.params = [W, b]
        self.grads = [np.zeros_like(W), np.zeros_like(b)]
        self.x = None
    
    # 順伝播
    def forward(self, x):
        self.x = x
        W, b = self.params
        out = np.dot(x, W) + b
        return out
    
    # 逆伝播
    def backward(self, dout):
        W, b = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        db = np.sum(dout, axis=0)

        self.grads[0][...] = dW
        self.grads[1][...] = db

        return dx

### Sigmoid

In [32]:
class Sigmoid:
    
    def __init__(self):
        self.params = []
        self.grads = []
        self.out = None

    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out
        return out
    
    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        return dx

In [33]:
sigmoid = Sigmoid()

In [34]:
x = np.array([1, 2, 4, -3])
sigmoid.forward(x)

array([0.73105858, 0.88079708, 0.98201379, 0.04742587])

In [35]:
dout = np.array([1, 3, 4, 5])
sigmoid.backward(dout)

array([0.19661193, 0.31498076, 0.07065082, 0.2258833 ])

#### ReLU関数

In [36]:
class ReLU:
    
    def __init__(self):
        self.params = []
        self.grads = []
        self.x = None
    
    def forward(self, x):
        self.x = x
        return np.maximum(0, x)
    
    def backward(self, dout):
        return np.where(self.x > 0, dout, 0)

In [37]:
x = np.array([1, 2, 4, -3])
dout = np.array([1, 3, 4, 5])

In [38]:
relu = ReLU()

In [39]:
relu.forward(x)

array([1, 2, 4, 0])

In [40]:
relu.backward(dout)

array([1, 3, 4, 0])

### Softmax with Loss

In [41]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
    
    # 教師データがOne-hot表現の場合
    # [ [0,0,1], [0,1,0] ] → [ [2], [1] ]
    if t.size == y.size:
        t = t.argmax(axis=1)
    
    batch_size = y.shape[0]
    return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size

In [42]:
class SoftmaxWithLoss():
    def __init__(self):
        self.params = []
        self.grads = []
        self.y = None
        self.t = None
    
    def forward(self, x, t):
        # 実測値
        self.t = t
        # 予測値
        self.y = softmax(x)

        if self.t.size == self.y.size:
            self.t = self.t.argmax(axis=1)
        loss = cross_entropy_error(self.y, self.t)
        return loss
    
    # ソフトマックスの逆伝播
    def backward(self, dout=1):
        batch_size = self.t.shape[0]

        dx = self.y.copy()
        # dx[np.arange(batch_size), self.t] -= 1
        # dx *= dout
        # dx = dx / batch_size
        if self.t.size == self.y.size: # 教師データがone-hot-vectorの場合
            dx = (self.y - self.t) / batch_size
            # forward()のLossの計算だとsumを計算してbatch_sizeで割っているため、
            # backward()の計算だとbatch_sizeで割って(乗算の逆伝播)、1を掛ける(sumの逆伝播)
        else:
            dx = self.y.copy()
            dx[np.arange(batch_size), self.t] -= 1 # 正解の時だけt=1を引く
            dx = dx / batch_size

        return dx

### 最適化手法
### SGD（確率的勾配降下法）

In [43]:
class SGD:
    def __init__(self, lr=0.01):
        self.lr = lr
    
    def update(self, params, grads):
        for i in range(len(params)):
            params[i] -= self.lr * grads[i]

### NNの構造

In [44]:
class NN:
    # 重みの初期化(W, b)
    def __init__(self, n_in, n_hidden, n_out):
        # W, bの初期化
        W1 = 0.01 * np.random.randn(n_in, n_hidden)
        b1 = np.zeros(n_hidden)
        W2 = 0.01 * np.random.randn(n_hidden, n_out)
        b2 = np.zeros(n_out)

        # レイヤを全てまとめる
        self.layers = [
            Affine(W1, b1),
            # ReLU(),
            Sigmoid(),
            Affine(W2, b2)
        ]

        self.loss_layer = SoftmaxWithLoss()
        
        # パラメータをまとめる
        self.params = []
        self.grads = []
        for layer in self.layers:
            self.params += layer.params
            self.grads += layer.grads
        
    # 推論
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x
    
    # 順伝播
    def forward(self, x, t):
        # 予測値
        y = self.predict(x)
        loss = self.loss_layer.forward(y, t)
        return loss
    
    # 逆伝播
    def backward(self, dout=1):
        dout = self.loss_layer.backward(dout)
        for layer in reversed(self.layers):
            dout = layer.backward(dout)
        return dout
    
    # 精度
    def accuracy(self, x, t):
        y = self.predict(x)
        y = np.argmax(y, axis=1)
        t = np.argmax(t, axis=1)

        accuracy = np.sum(y == t) / float(len(x))
        return accuracy

### データの準備

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('iris.csv')

In [ ]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
x = df.iloc[:, :-1]
x.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
t = df.iloc[:, -1]
t.head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int64

In [ ]:
print(x.shape)
print(t.shape)

(150, 4)
(150,)


In [ ]:
t = pd.get_dummies(t)
t

0  1  2
0    1  0  0
1    1  0  0
2    1  0  0
3    1  0  0
4    1  0  0
..  .. .. ..
145  0  0  1
146  0  0  1
147  0  0  1
148  0  0  1
149  0  0  1

[150 rows x 3 columns]

In [ ]:
x = x.values
t = t.values

### 学習に必要な準備

In [ ]:
epochs = 500
batch_size = 15
n_hidden = 10
lr = 0.1

In [ ]:
N = len(t)

In [ ]:
max_iters = N // batch_size
max_iters

10

In [ ]:
x.shape

(150, 4)

In [ ]:
model = NN(n_in=4, n_hidden=n_hidden, n_out=3)

In [ ]:
optimizer = SGD(lr=lr)

### 学習

In [ ]:
losses = []
loss_count = 0
total_loss = 0

for epoch in range(epochs):
    index = np.random.permutation(N)
    x = x[index]
    t = t[index]

    for iters in range(max_iters):
        batch_x = x[iters * batch_size: (iters + 1) * batch_size]
        batch_t = t[iters * batch_size: (iters + 1) * batch_size]

        # 順伝播
        loss = model.forward(batch_x, batch_t)
        # 勾配を算出
        model.backward()
        # 現在のパラメータの値と勾配情報を渡し、SGDを行う
        optimizer.update(model.params, model.grads)

        total_loss += loss
        loss_count += 1

        # 定期的に学習経過を出力
        if (iters + 1) % 10 == 0:
            ave_loss = total_loss / loss_count
            print('| epoch {}| iter {}/{}| loss {}'.format(epoch + 1, iters + 1, max_iters, round(ave_loss, 3)))
            losses.append(ave_loss)
            total_loss, loss_count = 0, 0