In [1]:
import numpy as np

### 入力から出力 (2 → 3)

In [4]:
# 2行3列
W1 = np.random.randn(2, 3)
W1

array([[ 1.74481176, -0.7612069 ,  0.3190391 ],
       [-0.24937038,  1.46210794, -2.06014071]])

In [6]:
b1 = np.random.randn(3)
b1

array([-0.3224172 , -0.38405435,  1.13376944])

In [7]:
b1.shape

(3,)

In [8]:
# サンプル数：10、入力変数：2
x = np.random.randn(10, 2)
x

array([[-1.09989127, -0.17242821],
       [-0.87785842,  0.04221375],
       [ 0.58281521, -1.10061918],
       [ 1.14472371,  0.90159072],
       [ 0.50249434,  0.90085595],
       [-0.68372786, -0.12289023],
       [-0.93576943, -0.26788808],
       [ 0.53035547, -0.69166075],
       [-0.39675353, -0.6871727 ],
       [-0.84520564, -0.67124613]])

In [9]:
x.shape

(10, 2)

In [10]:
W1.shape

(2, 3)

In [11]:
u1 = np.dot(x, W1) + b1
u1

array([[-2.19852194,  0.20108182,  1.1380875 ],
       [-1.86464176,  0.34589859,  0.76673203],
       [ 0.96894745, -2.43692135,  3.58714065],
       [ 1.45008018,  0.06279701, -0.35842269],
       [ 0.32969404,  0.55059212, -0.56180523],
       [-1.48474843, -0.04327476,  1.16880468],
       [-1.88835537, -0.06342149,  1.38710955],
       [ 0.77543295, -1.79904727,  2.72789204],
       [-0.84331691, -1.08676349,  2.42286201],
       [-1.62975305, -0.72211228,  2.24697728]])

In [12]:
u1.shape

(10, 3)

In [13]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [17]:
sigmoid(u1)

array([[0.0998833 , 0.55010175, 0.75732833],
       [0.13416293, 0.58562264, 0.68281354],
       [0.72490965, 0.08040024, 0.97306805],
       [0.81001077, 0.51569409, 0.41134144],
       [0.58168493, 0.63427296, 0.36312987],
       [0.18471127, 0.489183  , 0.76292889],
       [0.1314321 , 0.48414994, 0.8001304 ],
       [0.68469498, 0.14196708, 0.93865256],
       [0.30083666, 0.25222822, 0.91855412],
       [0.16386419, 0.32692801, 0.90438948]])

In [15]:
def relu(x):
    return np.maximum(0, x)

In [19]:
z1 = relu(u1)

In [20]:
z1

array([[0.        , 0.20108182, 1.1380875 ],
       [0.        , 0.34589859, 0.76673203],
       [0.96894745, 0.        , 3.58714065],
       [1.45008018, 0.06279701, 0.        ],
       [0.32969404, 0.55059212, 0.        ],
       [0.        , 0.        , 1.16880468],
       [0.        , 0.        , 1.38710955],
       [0.77543295, 0.        , 2.72789204],
       [0.        , 0.        , 2.42286201],
       [0.        , 0.        , 2.24697728]])

### 中間から出力(3 → 2)

In [21]:
W2 = np.random.randn(3, 2)
W2

array([[-0.0126646 , -1.11731035],
       [ 0.2344157 ,  1.65980218],
       [ 0.74204416, -0.19183555]])

In [22]:
b2 = np.random.randn(2)
b2

array([-0.88762896, -0.74715829])

In [23]:
u2 = np.dot(z1, W2) + b2

In [24]:
u2

array([[ 0.00401895, -0.6317279 ],
       [-0.23759588, -0.32012153],
       [ 1.76191648, -2.51791442],
       [-0.89127304, -2.26311727],
       [-0.76273697, -0.20165486],
       [-0.02032428, -0.97137659],
       [ 0.14166757, -1.01325522],
       [ 1.12676685, -2.13686424],
       [ 0.91024164, -1.21194937],
       [ 0.7797274 , -1.17820842]])

In [28]:
def softmax(x):
    # オーバーフロー対策
    exp_x = np.exp(x - np.max(x))
    return np.exp(x) / np.sum(exp_x)

In [30]:
y = softmax(u2[0])
y

array([0.65642424, 0.3476028 ])

In [31]:
np.argmax(y)

0

In [32]:
def softmax(x):
    if x.ndim == 2:
        x = x - x.max(axis=1, keepdims=True)
        x = np.exp(x)
        x /= x.sum(axis=1, keepdims=True)
    elif x.ndim == 1:
        x = x - np.max(x)
        x = np.exp(x) / np.sum(np.exp(x))
    return x

In [36]:
softmax(u2)

array([[0.6537914 , 0.3462086 ],
       [0.52061971, 0.47938029],
       [0.98634406, 0.01365594],
       [0.79767795, 0.20232205],
       [0.36329712, 0.63670288],
       [0.72132676, 0.27867324],
       [0.76040894, 0.23959106],
       [0.96315985, 0.03684015],
       [0.89304139, 0.10695861],
       [0.87630939, 0.12369061]])

### レイヤーとしてまとめていく
- 変数
    - パラメータ(params)
    - 勾配(grads)
- メソッド
    - 順伝播(forward)
    - 逆伝播(backward)

### Affine変換(線形変換)

In [37]:
class Affine:
    # パラメータの初期化
    def __init__(self, W, b):
        self.params = [W, b]
    
    # 順伝播
    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out

### ReLU関数（非線形変換）

In [38]:
class ReLU:
    def __init__(self):
        self.params = []
    
    def forward(self, x):
        return np.maximum(0, x)

In [39]:
W1 = np.random.randn(2, 3)
b1 = np.random.randn(3)

W2 = np.random.randn(3, 2)
b2 = np.random.randn(2)

In [40]:
class NN:
    # 重みの初期化(W, b)
    def __init__(self, n_in, n_hidden, n_out):
        # W, bの初期化
        W1 = np.random.randn(n_in, n_hidden)
        b1 = np.random.randn(n_hidden)
        W2 = np.random.randn(n_hidden, n_out)
        b2 = np.random.randn(n_out)

        # レイヤを全てまとめる
        self.layers = [
            Affine(W1, b1),
            ReLU(),
            Affine(W2, b2)
        ]
        
        # パラメータをまとめる
        self.params = []
        for layer in self.layers:
            self.params += layer.params
        
    # 推論
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [41]:
x = np.random.randn(10, 4)
x

array([[-0.75439794,  1.25286816,  0.51292982, -0.29809284],
       [ 0.48851815, -0.07557171,  1.13162939,  1.51981682],
       [ 2.18557541, -1.39649634, -1.44411381, -0.50446586],
       [ 0.16003707,  0.87616892,  0.31563495, -2.02220122],
       [-0.30620401,  0.82797464,  0.23009474,  0.76201118],
       [-0.22232814, -0.20075807,  0.18656139,  0.41005165],
       [ 0.19829972,  0.11900865, -0.67066229,  0.37756379],
       [ 0.12182127,  1.12948391,  1.19891788,  0.18515642],
       [-0.37528495, -0.63873041,  0.42349435,  0.07734007],
       [-0.34385368,  0.04359686, -0.62000084,  0.69803203]])

In [42]:
model = NN(4, 10, 3)

In [43]:
model.predict(x)

array([[-1.64915378,  0.36231964,  1.48021724],
       [ 0.08266148, -5.8156644 , -6.01614048],
       [ 6.73220907,  2.75491817,  0.89939848],
       [ 1.90818478,  5.57306294, -0.16727686],
       [-0.86463622, -1.18337273,  1.77004127],
       [-1.37576578,  0.97101115, -0.83533382],
       [ 0.2402391 , -0.24383568,  3.2313066 ],
       [-0.17091574, -3.8862464 , -3.60792349],
       [-1.19868817,  3.26267812, -1.39029235],
       [-0.59941945, -0.71819385,  3.97607829]])

### 逆伝播


### Affine

In [44]:
class Affine:
    # パラメータの初期化
    def __init__(self, W, b):
        self.params = [W, b]
        self.grads = [np.zeros_like(W), np.zeros_like(b)]
        self.x = None
    
    # 順伝播
    def forward(self, x):
        self.x = x
        W, b = self.params
        out = np.dot(x, W) + b
        return out
    
    # 逆伝播
    def backward(self, dout):
        W, b = self.params
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        db = np.sum(dout, axis=0)

        self.grads[0][...] = dW
        self.grads[1][...] = db

        return dx

### Sigmoid

In [45]:
class Sigmoid:
    
    def __init__(self):
        self.params = []
        self.grads = []
        self.out = None

    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out
        return out
    
    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        return dx

In [46]:
sigmoid = Sigmoid()

In [48]:
x = np.array([1, 2, 4, -3])
sigmoid.forward(x)

array([0.73105858, 0.88079708, 0.98201379, 0.04742587])

In [49]:
dout = np.array([1, 3, 4, 5])
sigmoid.backward(dout)

array([0.19661193, 0.31498076, 0.07065082, 0.2258833 ])

#### ReLU関数

In [50]:
class ReLU:
    
    def __init__(self):
        self.params = []
        self.grads = []
        self.x = None
    
    def forward(self, x):
        self.x = x
        return np.maximum(0, x)
    
    def backward(self, dout):
        return np.where(self.x > 0, dout, 0)

In [51]:
x = np.array([1, 2, 4, -3])
dout = np.array([1, 3, 4, 5])

In [52]:
relu = ReLU()

In [53]:
relu.forward(x)

array([1, 2, 4, 0])

In [54]:
relu.backward(dout)

array([1, 3, 4, 0])

### Softmax with Loss

In [105]:
def cross_entropy_error(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)
    
    # 教師データがOne-hot表現の場合
    # [ [0,0,1], [0,1,0] ] → [ [2], [1] ]
    if t.size == y.size:
        t = t.argmax(axis=1)
    
    batch_size = y.shape[0]
    return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size

In [107]:
class SoftmaxWithLoss():
    def __init__(self):
        self.params = []
        self.grads = []
        self.y = None
        self.t = None
    
    def forward(self, x, t):
        # 実測値
        self.t = t
        # 予測値
        self.y = softmax(y)

        if self.t.size == self.y.size:
            self.t = self.t.argmax(axis=1)
        loss = cross_entropy_error(self.y, self.t)
        return loss
    
    # ソフトマックスの逆伝播
    def backward(self, dout=1):
        batch_size = self.t.shape[0]

        dx = self.y.copy()
        # dx[np.arange(batch_size), self.t] -= 1
        # dx *= dout
        # dx = dx / batch_size
        if self.t.size == self.y.size: # 教師データがone-hot-vectorの場合
            dx = (self.y - self.t) / batch_size
            # forward()のLossの計算だとsumを計算してbatch_sizeで割っているため、
            # backward()の計算だとbatch_sizeで割って(乗算の逆伝播)、1を掛ける(sumの逆伝播)
        else:
            dx = self.y.copy()
            dx[np.arange(batch_size), self.t] -= 1 # 正解の時だけt=1を引く
            dx = dx / batch_size

        return dx

### 最適化手法
### SGD（確率的勾配降下法）

In [108]:
class SGD:
    def __init__(self, lr=0.01):
        self.lr = lr
    
    def update(self, params, grads):
        for i in range(len(params)):
            params[i] -= self.lr * grads[i]

### NNの構造

In [109]:
class NN:
    # 重みの初期化(W, b)
    def __init__(self, n_in, n_hidden, n_out):
        # W, bの初期化
        W1 = 0.01 * np.random.randn(n_in, n_hidden)
        b1 = np.zeros(n_hidden)
        W2 = 0.01 * np.random.randn(n_hidden, n_out)
        b2 = np.zeros(n_out)

        # レイヤを全てまとめる
        self.layers = [
            Affine(W1, b1),
            # ReLU(),
            Sigmoid(),
            Affine(W2, b2)
        ]

        self.loss_layer = SoftmaxWithLoss()
        
        # パラメータをまとめる
        self.params = []
        self.grads = []
        for layer in self.layers:
            self.params += layer.params
            self.grads += layer.grads
        
    # 推論
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x
    
    # 順伝播
    def forward(self, x, t):
        # 予測値
        y = self.predict(x)
        loss = self.loss_layer.forward(y, t)
        return loss
    
    # 逆伝播
    def backward(self, dout=1):
        dout = self.loss_layer.backward(dout)
        for layer in reversed(self.layers):
            dout = layer.backward(dout)
        return dout
    
    # 制度
    def accuracy(self, x, t):
        y = self.predict(x)
        y = np.argmax(y, axis=1)
        t = np.argmax(t, axis=1)

        accuracy = np.sum(y == t) / float(len(x))
        return accuracy

### データの準備

In [110]:
import pandas as pd

In [111]:
df = pd.read_csv('iris.csv')

In [112]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [113]:
x = df.iloc[:, :-1]
x.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [114]:
t = df.iloc[:, -1]
t.head()

0    0
1    0
2    0
3    0
4    0
Name: species, dtype: int64

In [115]:
print(x.shape)
print(t.shape)

(150, 4)
(150,)


In [116]:
t = pd.get_dummies(t)
t

0  1  2
0    1  0  0
1    1  0  0
2    1  0  0
3    1  0  0
4    1  0  0
..  .. .. ..
145  0  0  1
146  0  0  1
147  0  0  1
148  0  0  1
149  0  0  1

[150 rows x 3 columns]

In [117]:
x = x.values
t = t.values

### 学習に必要な準備

In [118]:
epochs = 500
batch_size = 15
n_hidden = 10
lr = 0.1

In [119]:
N = len(t)

In [120]:
max_iters = N // batch_size
max_iters

10

In [121]:
x.shape

(150, 4)

In [122]:
model = NN(n_in=4, n_hidden=n_hidden, n_out=3)

In [123]:
optimizer = SGD(lr=lr)

### 学習

In [125]:
losses = []
loss_count = 0
total_loss = 0

for epoch in range(epochs):
    index = np.random.permutation(N)
    x = x[index]
    t = t[index]

    for iters in range(max_iters):
        batch_x = x[iters * batch_size: (iters + 1) * batch_size]
        batch_t = t[iters * batch_size: (iters + 1) * batch_size]

        # 順伝播
        loss = model.forward(batch_x, batch_t)
        # 勾配を算出
        model.backward()
        # 現在のパラメータの値と勾配情報を渡し、SGDを行う
        optimizer.update(model.params, model.grads)

        total_loss += loss
        loss_count += 1

        # 定期的に学習経過を出力
        if (iters + 1) % 10 == 0:
            ave_loss = total_loss / loss_count
            print('| epoch {}| iter {}/{}| loss {}'.format(epoch + 1, iters + 1, max_iters, round(ave_loss, 3)))
            losses.append(ave_loss)
            total_loss, loss_count = 0, 0