In [1]:
import numpy as np

In [2]:
x = np.random.randint(1, 10, (40, 4))
x

array([[5, 9, 8, 1],
       [4, 5, 5, 9],
       [3, 4, 8, 3],
       [9, 7, 3, 2],
       [4, 6, 2, 1],
       [9, 3, 3, 6],
       [1, 7, 3, 3],
       [8, 7, 6, 1],
       [5, 5, 4, 8],
       [5, 3, 7, 2],
       [7, 8, 5, 3],
       [8, 5, 1, 4],
       [3, 2, 9, 9],
       [6, 6, 5, 9],
       [3, 2, 9, 1],
       [7, 9, 4, 4],
       [6, 9, 5, 2],
       [3, 6, 7, 9],
       [3, 5, 6, 2],
       [9, 8, 5, 2],
       [8, 2, 9, 7],
       [4, 5, 4, 9],
       [4, 9, 3, 1],
       [2, 6, 5, 3],
       [4, 4, 7, 4],
       [6, 2, 8, 1],
       [9, 4, 8, 5],
       [1, 2, 8, 5],
       [3, 6, 6, 3],
       [5, 3, 7, 7],
       [4, 3, 7, 2],
       [8, 6, 5, 9],
       [4, 7, 4, 7],
       [1, 5, 3, 1],
       [1, 1, 9, 5],
       [7, 3, 4, 8],
       [9, 8, 1, 6],
       [8, 3, 1, 4],
       [9, 4, 8, 9],
       [4, 1, 5, 3]])

In [3]:
x.shape

(40, 4)

In [4]:
# 全体のデータ数を取得
data_size = x.shape[0]
data_size

40

In [5]:
# バッチサイズを指定
batch_size = 5

In [6]:
# ランダムで数値を抽出
# replace=False　重複不許可
np.random.choice(data_size, batch_size, replace=False)

array([28, 30, 21, 15,  5])

In [8]:
mini_batch = x[np.random.choice(data_size, batch_size, replace=False)]
mini_batch

array([[7, 9, 4, 4],
       [8, 2, 9, 7],
       [7, 8, 5, 3],
       [5, 3, 7, 7],
       [8, 7, 6, 1]])

In [11]:
mu = np.mean(mini_batch, axis=0)

In [12]:
var = np.var(mini_batch, axis=0)

In [13]:
(mini_batch - mu) / np.sqrt(var + 1e-8)

array([[ 0.        ,  1.14873305, -1.27872402, -0.17149858],
       [ 0.91287093, -1.3641205 ,  1.62746694,  1.1147408 ],
       [ 0.        ,  0.78975397, -0.69748583, -0.60024505],
       [-1.82574185, -1.00514142,  0.46499055,  1.1147408 ],
       [ 0.91287093,  0.43077489, -0.11624764, -1.45773797]])

In [14]:
def batch_norm(X, gamma=1, beta=0):
    mu = np.mean(X, axis=0)
    var = np.var(X, axis=0)
    X_norm = (X - mu) / np.sqrt(var + 1e-8)
    out = gamma * X_norm + beta
    return out

In [15]:
batch_norm(mini_batch)

array([[ 0.        ,  1.14873305, -1.27872402, -0.17149858],
       [ 0.91287093, -1.3641205 ,  1.62746694,  1.1147408 ],
       [ 0.        ,  0.78975397, -0.69748583, -0.60024505],
       [-1.82574185, -1.00514142,  0.46499055,  1.1147408 ],
       [ 0.91287093,  0.43077489, -0.11624764, -1.45773797]])