In [1]:
import numpy as np

In [2]:
x = np.random.randint(1, 10, (40, 4))
x

array([[6, 7, 9, 9],
       [6, 6, 3, 6],
       [8, 2, 9, 7],
       [8, 1, 7, 3],
       [2, 6, 4, 7],
       [5, 7, 4, 4],
       [2, 3, 6, 7],
       [7, 6, 6, 8],
       [3, 9, 5, 9],
       [7, 3, 4, 3],
       [5, 8, 8, 7],
       [8, 6, 7, 6],
       [5, 2, 6, 3],
       [9, 8, 8, 6],
       [7, 8, 2, 8],
       [2, 6, 8, 4],
       [1, 8, 3, 6],
       [4, 5, 5, 9],
       [8, 8, 1, 2],
       [4, 4, 6, 7],
       [2, 1, 8, 1],
       [5, 8, 4, 2],
       [2, 5, 6, 9],
       [2, 8, 1, 6],
       [6, 7, 6, 4],
       [8, 6, 3, 6],
       [5, 8, 1, 5],
       [1, 1, 8, 7],
       [8, 5, 7, 2],
       [6, 8, 8, 6],
       [7, 3, 3, 4],
       [3, 7, 2, 1],
       [5, 6, 4, 9],
       [4, 5, 5, 8],
       [2, 2, 9, 4],
       [5, 3, 9, 1],
       [7, 1, 8, 9],
       [4, 7, 6, 4],
       [9, 8, 9, 3],
       [5, 3, 3, 1]])

In [3]:
x.shape

(40, 4)

In [4]:
# 全体のデータ数を取得
data_size = x.shape[0]
data_size

40

In [5]:
# バッチサイズを指定
batch_size = 5

In [6]:
# ランダムで数値を抽出
# replace=False　重複不許可
np.random.choice(data_size, batch_size, replace=False)

array([ 1, 32,  0, 39, 34])

In [7]:
mini_batch = x[np.random.choice(data_size, batch_size, replace=False)]
mini_batch

array([[8, 6, 7, 6],
       [9, 8, 8, 6],
       [8, 5, 7, 2],
       [7, 1, 8, 9],
       [2, 6, 8, 4]])

In [8]:
mu = np.mean(mini_batch, axis=0)

In [13]:
mu

array([6.8, 5.2, 7.6, 5.4])

In [9]:
var = np.var(mini_batch, axis=0)

In [14]:
var

array([6.16, 5.36, 0.24, 5.44])

In [10]:
(mini_batch - mu) / np.sqrt(var + 1e-8)

array([[ 0.48349378,  0.34554737, -1.22474485,  0.25724788],
       [ 0.88640526,  1.20941579,  0.81649656,  0.25724788],
       [ 0.48349378, -0.08638684, -1.22474485, -1.45773797],
       [ 0.0805823 , -1.81412369,  0.81649656,  1.54348726],
       [-1.93397511,  0.34554737,  0.81649656, -0.60024505]])

In [11]:
def batch_norm(X, gamma=1, beta=0):
    mu = np.mean(X, axis=0)
    var = np.var(X, axis=0)
    X_norm = (X - mu) / np.sqrt(var + 1e-8)
    out = gamma * X_norm + beta
    return out

In [12]:
batch_norm(mini_batch)

array([[ 0.48349378,  0.34554737, -1.22474485,  0.25724788],
       [ 0.88640526,  1.20941579,  0.81649656,  0.25724788],
       [ 0.48349378, -0.08638684, -1.22474485, -1.45773797],
       [ 0.0805823 , -1.81412369,  0.81649656,  1.54348726],
       [-1.93397511,  0.34554737,  0.81649656, -0.60024505]])